name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
